spring:
  application:
    name: financeflow
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  messages:
    basename: messages,budgeting.messages
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 900000

brevo:
  api-key: ${BREVO_API_KEY}
  url: ${BREVO_URL:https://api.brevo.com/v3/smtp/email}
  sender:
    name: ${BREVO_SENDER_NAME:financeflow}
    email: ${BREVO_SENDER_EMAIL}

logging:
  level:
    com.samuelgularte: DEBUG
    org.springframework.ai: DEBUG
