spring:
  application:
    name: financeflow
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  app:
    jwtSecret: ${JWT_SECRET}
    jwtExpirationMs: 172800000
logging:
  level:
    com.samuelgularte: DEBUG
